'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { AlertCircle, ArrowLeft, Eye, EyeOff, LockKeyhole, Phone } from 'lucide-react';
import api from '@/lib/axios';
import { useAuthStore, type AuthUser } from '@/store/useAuthStore';
import { getErrorDetails } from '@/lib/errorDetails';

const copies={ru:{title:'Вход в AVERON',intro:'Введите номер и пароль. Затем подтвердите вход кодом из SMS.',sent:'Код отправлен на',phone:'Номер телефона',password:'Пароль',forgot:'Забыли пароль?',sms:'Код из SMS',wait:'Подождите…',next:'Продолжить',confirm:'Подтвердить и войти',change:'Изменить данные',noAccount:'Нет аккаунта?',register:'Зарегистрируйтесь',error:'Не удалось выполнить запрос'},uz:{title:'AVERON’ga kirish',intro:'Telefon raqami va parolni kiriting. So‘ng SMS kod bilan tasdiqlang.',sent:'Kod yuborildi:',phone:'Telefon raqami',password:'Parol',forgot:'Parolni unutdingizmi?',sms:'SMS kodi',wait:'Kuting…',next:'Davom etish',confirm:'Tasdiqlash va kirish',change:'Ma’lumotlarni o‘zgartirish',noAccount:'Akkauntingiz yo‘qmi?',register:'Ro‘yxatdan o‘ting',error:'So‘rovni bajarib bo‘lmadi'},en:{title:'Sign in to AVERON',intro:'Enter your phone and password, then confirm with the SMS code.',sent:'Code sent to',phone:'Phone number',password:'Password',forgot:'Forgot password?',sms:'SMS code',wait:'Please wait…',next:'Continue',confirm:'Confirm and sign in',change:'Change details',noAccount:'No account?',register:'Create one',error:'The request could not be completed'}} as const;

export function LoginForm({locale}:{locale:string}){
 const c=copies[locale as keyof typeof copies]||copies.ru; const router=useRouter(); const setAuth=useAuthStore(s=>s.setAuth);
 const [phone,setPhone]=useState('+998 '),[password,setPassword]=useState(''),[code,setCode]=useState(''); const [step,setStep]=useState<'credentials'|'code'>('credentials'); const [show,setShow]=useState(false),[loading,setLoading]=useState(false); const [error,setError]=useState('');
 const submit=async()=>{setLoading(true);setError('');try{if(step==='credentials'){await api.post('/auth/login/phone/request-code',{phone,password});setStep('code');}else{const {data}=await api.post<{accessToken:string;user:AuthUser}>('/auth/login/phone/verify-code',{phone,code});setAuth(data.user,data.accessToken);router.replace(`/${locale}`);}}catch(v: unknown){setError(getErrorDetails(v).message||c.error);}finally{setLoading(false);}};
 const field='h-12 w-full rounded-xl border border-white/10 bg-white/5 text-white outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500/20';
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-white">{c.title}</h1><p className="mt-1.5 text-sm text-stone-400">{step==='credentials'?c.intro:`${c.sent} ${phone}`}</p></div>{error&&<div className="flex gap-3 rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-400"><AlertCircle size={16}/>{error}</div>}<form onSubmit={e=>{e.preventDefault();void submit();}} className="space-y-4">{step==='credentials'?<><label className="block space-y-2"><span className="text-xs font-semibold uppercase tracking-wider text-stone-400">{c.phone}</span><div className="relative"><Phone size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-stone-500"/><input value={phone} onChange={e=>setPhone(e.target.value)} autoComplete="tel" inputMode="tel" className={`${field} pl-11 pr-4`}/></div></label><label className="block space-y-2"><span className="text-xs font-semibold uppercase tracking-wider text-stone-400">{c.password}</span><div className="relative"><LockKeyhole size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-stone-500"/><input type={show?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" className={`${field} pl-11 pr-11`}/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3.5 top-1/2 -translate-y-1/2 text-stone-500">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label><div className="flex justify-end"><Link href={`/${locale}/forgot-password`} className="text-sm font-semibold text-primary-400">{c.forgot}</Link></div></>:<label className="block space-y-2"><span className="text-xs font-semibold uppercase tracking-wider text-stone-400">{c.sms}</span><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} autoFocus inputMode="numeric" className={`${field} h-14 px-4 text-center text-2xl font-bold tracking-[.45em]`}/></label>}<button disabled={loading||(step==='credentials'?(!phone||!password):code.length!==6)} className="h-12 w-full rounded-xl bg-primary-600 font-semibold text-white disabled:opacity-50">{loading?c.wait:step==='credentials'?c.next:c.confirm}</button></form>{step==='code'&&<button onClick={()=>{setStep('credentials');setCode('');}} className="mx-auto flex items-center gap-2 text-sm text-stone-400"><ArrowLeft size={15}/>{c.change}</button>}<p className="text-center text-sm text-stone-500">{c.noAccount} <Link href={`/${locale}/register`} className="font-semibold text-primary-400">{c.register}</Link></p></div>;
}
